name: markdown lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # set specific OS version
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1

    # installing more packages as proposed in 
    # https://askubuntu.com/questions/1088662/npm-depends-node-gyp-0-10-9-but-it-is-not-going-to-be-installed
    - name: install markdownlint-cli
      run: |
        sudo apt-get update       
        sudo apt-get install -y npm sudo nodejs node-gyp libssl-dev
        npm install markdownlint-cli

    - name: lint markdown files
      run: node_modules/.bin/markdownlint .
